version: "3.9"

services:
  postgres:
    image: postgres
    container_name: tattoo-book-database
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host

  rabbitmq:
    image: rabbitmq:3-management
    container_name: tattoo-book-rabbitmq
    restart: always
    env_file: .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    network_mode: host

volumes:
  postgres_data:
  rabbitmq_data:
