services:
  app:
    build:
      context: ../../
      dockerfile: ./deploy/dev/Dockerfile
    container_name: tattoo-book-backend
    env_file: .env
    network_mode: host
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    deploy:
      resources:
        limits:
          memory: 200M
